### ISSUE TITLE
A question out of curiosity

### ISSUE THREAD

**Issue by c8ef** [junaire/jcc#4]
The ci of this project is targeted at Windows, macOS, and Linux. So will the jcc compiler support both Linux and **Windows** abi or calling conventions? That seems like a lot of work!

**Comment by junaire** [comment]
That's hard to say in fact... For now, the compiler is really just my toy project and I don't how it will go (Maybe I will abandon it at some point) But I guess it will only support Itanium ABI, cuz that's already lots of work to do. The reason why CI targets 3 platforms is that I want each 3 major compilers (GCC, Clang, MSVC) to help me check some issues in my code that other ones can not...

**Comment by c8ef** [comment]
I see. I read about SQLite using the [same strategy](https://www.sqlite.org/testing.html#undefined_behavior_checks), too.
Thanks for your reply!
